# Generated by Django 4.0.4 on 2022-09-29 16:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profiles.default-image.png', null=True, upload_to=account.models.upload_to),
        ),
    ]
