# Generated by Django 4.1.1 on 2022-10-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='public_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
