# Generated by Django 4.1.1 on 2022-10-15 09:59

import centre.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stars', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCentreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
                ('has_payment_category', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('close', 'close')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.eventcentre')),
            ],
        ),
        migrations.CreateModel(
            name='HallPaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weekday', 'weekday'), ('weekend', 'weekend'), ('festive_period', 'festive_period')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.hall')),
            ],
            options={
                'verbose_name_plural': 'Hall payment Categories',
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=centre.models.upload_to_hall)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.hall')),
            ],
        ),
        migrations.CreateModel(
            name='EventCentreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=centre.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centre_image', to='centre.eventcentre')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField()),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_booked', to='centre.hall')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
