# Generated by Django 4.0.4 on 2022-09-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcentreimage',
            name='event_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centre_image', to='centre.eventcentre'),
        ),
    ]
