# Generated by Django 4.1.1 on 2022-09-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_alter_eventcentreimage_event_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_centre',
        ),
        migrations.AddField(
            model_name='booking',
            name='event_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_centre', to='centre.eventcentre'),
        ),
    ]
